### ISSUE TITLE
clone this proj fails

### ISSUE THREAD

**Issue by JieFengWang** [mti-lab/rnn-descent#1]
Hi @nono927 , I notice the instructions in README.md that letting us to clone via `ssh`. after I try clone this proj in my ubuntu machine, it shows`git@github.com: Permission denied (publickey).`

Then I tried to clone via `http` channel , and clone the latest Faiss library as sub-folder. The `cmake ` cmd is fine, but the `make` cmd fails with lots of errors. 

How can I clone and install your proj with ease, thanks.

**Comment by nono927** [comment]
Thank you for your report!

> clone the latest Faiss library as sub-folder. 

Please do not clone the latest Faiss repository and use the following command instead.
```
git clone --recursive https://github.com/mti-lab/rnn-descent.git
``` 
You can use the `--recursive` option even if you clone this repo via http.

> The cmake  cmd is fine, but the make cmd fails with lots of errors.

I found an error and fixed it. If you clone this repo again with the above command, the build will succeed (but lots of warning might occur).

**Comment by nono927** [comment]
@JieFengWang Sorry, I missed the mention

**Comment by JieFengWang** [comment]
> Thank you for your report!
> 
> > clone the latest Faiss library as sub-folder.
> 
> Please do not clone the latest Faiss repository and use the following command instead.
> 
> ```
> git clone --recursive https://github.com/mti-lab/rnn-descent.git
> ```
> 
> You can use the `--recursive` option even if you clone this repo via http.
> 
> > The cmake  cmd is fine, but the make cmd fails with lots of errors.
> 
> I found an error and fixed it. If you clone this repo again with the above command, the build will succeed (but lots of warning might occur).

Hi @nono927 , thanks for your reply. 

The default port number for ssh on my physical machine is not 22, so it failed and prompted some errors, for example:
```shell
ssh: connect to host github.com port 2345: Connection timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

So I clone in ubuntu docker and it still fails （I think it has something to do with the fact that after the rnn project is cloned via http, while the submodule faiss is still cloned via ssh）:

```shell
root@b7afe47ada28:~/rnn# git clone --recursive https://github.com/mti-lab/rnn-descent.git
Cloning into 'rnn-descent'...
remote: Enumerating objects: 45, done.
remote: Counting objects: 100% (45/45), done.
remote: Compressing objects: 100% (33/33), done.
remote: Total 45 (delta 11), reused 38 (delta 8), pack-reused 0
Receiving objects: 100% (45/45), 17.98 KiB | 1.28 MiB/s, done.
Resolving deltas: 100% (11/11), done.
Submodule 'faiss' (git@github.com:facebookresearch/faiss.git) registered for path 'faiss'
Cloning into '/root/rnn/rnn-descent/faiss'...
The authenticity of host 'github.com (140.82.112.4)' can't be established.
ED25519 key fingerprint is SHA256:+DiY3wvvV6TuJJhbpZisF/zLDA0zPMSvHdkr4UvCOqU.
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'github.com' (ED25519) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:facebookresearch/faiss.git' into submodule path '/root/rnn/rnn-descent/faiss' failed
Failed to clone 'faiss'. Retry scheduled
Cloning into '/root/rnn/rnn-descent/faiss'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:facebookresearch/faiss.git' into submodule path '/root/rnn/rnn-descent/faiss' failed
Failed to clone 'faiss' a second time, aborting
```

**Comment by JieFengWang** [comment]
Update info: `mini_rnn` a re-implementation of Faiss-free Relative NN-Descent. I re-organized the code to make it easy to run. [github url](https://github.com/JieFengWang/mini_rnn)
